# Generated by Django 4.1.3 on 2022-12-13 10:12

import communication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.TextField(choices=[('R', 'Resolved'), ('U', 'Unresolved'), ('F', 'Frozen')], default=communication.utils.Status['U'], max_length=254),
        ),
    ]
